---
- name: Create Vaultwarden Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ vaultwarden_data_directory }}"

- name: Vaultwarden Docker Container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    pull: true
    ports:
      - "{{ vaultwarden_port_a }}:80"
      - "{{ vaultwarden_port_b }}:3012"
    volumes:
      - "{{ vaultwarden_data_directory }}:/data:rw"
    env:
      SIGNUPS_ALLOWED: "{{ vaultwarden_allow_signups }}"
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
      LOG_LEVEL: "debug"
      LOG_FILE: "/data/vaultwarden.log"
      WEBSOCKET_ENABLED: "false"
      TZ: "{{ ansible_nas_timezone }}"
    labels:
      traefik.enable: "false"
      traefik.http.routers.vaultwarden.rule: "Host(`{{ vaultwarden_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.vaultwarden.tls: "true"
      traefik.http.routers.vaultwarden.tls.certresolver: "letsencrypt"
      traefik.http.routers.vaultwarden.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.vaultwarden.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.routers.vaultwarden.service: "vaultwarden"
#      traefik.http.routers.vaultwarden.middlewares: "vaultwarden-ipwhitelist@docker"
#      traefik.http.routers.vaultwarden.middlewares: "my-auth@file"
      traefik.http.services.vaultwarden.loadbalancer.server.port: "80"
#      traefik.http.middlewares.vaultwarden-ipwhitelist.ipwhitelist.sourcerange: "{{ vaultwarden_ip_whitelist }}"
      traefik.http.routers.vaultwarden-ws.rule: "Host(`{{ vaultwarden_hostname }}.{{ ansible_nas_domain }}`) && Path(`/notifications/hub`)"
      traefik.http.routers.vaultwarden-ws.tls: "true"
      traefik.http.routers.vaultwarden-ws.tls.certresolver: "letsencrypt"
      traefik.http.routers.vaultwarden-ws.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.vaultwarden-ws.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.routers.vaultwarden-ws.service: "vaultwarden-ws"
#      traefik.http.routers.vaultwarden-ws.middlewares: "vaultwarden-ipwhitelist@docker"
#      traefik.http.routers.vaultwarden-ws.middlewares: "my-auth@file"
      traefik.http.services.vaultwarden-ws.loadbalancer.server.port: "3012"
#      traefik.http.middlewares.vaultwarden-ipwhitelist.ipwhitelist.sourcerange: "{{ vaultwarden_ip_whitelist }}"
    memory: "{{ vaultwarden_memory }}"
    restart_policy: unless-stopped

- name: Vaultwarden Backup Container
  docker_container:
    name: vaultwarden-backup
    image: bruceforce/vaultwarden-backup:latest
    pull: true
    restart_policy: unless-stopped
    volumes_from: vaultwarden
    memory: "{{ vaultwarden_backup_memory }}"
