---
- name: Create Traefik Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_data_directory }}"
    - "{{ traefik_data_directory }}/letsencrypt"

- name: Template Traefik config.toml
  template:
    src: traefik.toml
    dest: "{{ traefik_data_directory }}/traefik.toml"
  register: template_config

- name: Template Traefik dynamic.toml
  template:
    src: dynamic.toml
    dest: "{{ traefik_data_directory }}/dynamic.toml"
  register: dynamic_template_config

- name: Usersfile for basic auth
  template:
    src: usersFile
    dest: "{{ traefik_data_directory }}/usersFile"
  register: usersfile_basicauth_config

- name: Traefik Docker Container
  docker_container:
    name: traefik
    image: "{{ traefik_docker_image }}"
    pull: true
    network_mode: host
    volumes:
      - "{{ traefik_data_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
      - "{{ traefik_data_directory }}/dynamic.toml:/etc/traefik/dynamic.toml:ro"
      - "{{ traefik_data_directory }}/usersFile:/etc/traefik/usersFile:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env: "{{ traefik_environment_variables }}"
    restart_policy: unless-stopped
    memory: "{{ traefik_memory }}"
    recreate: "{{ template_config is changed }}"
