---
- name: Create monica Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ monica_config_directory }}"
    - "{{ monica_data_directory }}"

- name: Create monica network
  docker_network:
    name: "{{ monica_container_network_name }}"

- name: Create MySQL container for monica
  docker_container:
    name: monica-mysql
    image: mysql:5.7
    pull: true
    volumes:
      - "{{ monica_data_directory }}/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "monica"
      MYSQL_USER: "{{ monica_mysql_user }}"
      MYSQL_PASSWORD: "{{ monica_mysql_password }}"
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    memory: "{{ monica_mysql_memory }}"
    networks:
      - name: "{{ monica_container_network_name }}"

- name: monica Docker Container
  docker_container:
    name: monica
    image: monica
    pull: true
    volumes:
      - "{{ monica_config_directory }}:/var/www/html/storage:rw"
    ports:
      - "{{ monica_port }}:80"
    env:
      DB_CONNECTION: "mysql"
      APP_KEY: "{{ monica_app_key }}"
      DB_HOST: "monica-mysql"
      DB_USERNAME: "{{ monica_mysql_user }}"
      DB_PASSWORD: "{{ monica_mysql_password }}"
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    memory: "{{ monica_memory }}"
    networks:
      - name: "{{ monica_container_network_name }}"
    labels:
      traefik.enable: "{{ monica_available_externally | string }}"
      traefik.http.routers.monica.rule: "Host(`{{ monica_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.monica.tls.certresolver: "letsencrypt"
      traefik.http.routers.monica.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.monica.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.monica.loadbalancer.server.port: "80"
